-- 04_create_province_canton_parish_tables.sql
-- Crea tablas provincias, cantones y parroquias (estructura mínima)

CREATE TABLE PROVINCIAS (
  PROVINCIAID NUMBER(10) PRIMARY KEY,
  NOMBRE VARCHAR2(200) NOT NULL
);

CREATE SEQUENCE SEQ_PROVINCIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_PROVINCIA_BI
BEFORE INSERT ON PROVINCIAS
FOR EACH ROW
BEGIN
  IF :NEW.PROVINCIAID IS NULL THEN
    :NEW.PROVINCIAID := SEQ_PROVINCIA.NEXTVAL;
  END IF;
END;
/

CREATE TABLE CANTONES (
  CANTONID NUMBER(10) PRIMARY KEY,
  PROVINCIAID NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(200) NOT NULL,
  CONSTRAINT FK_CANTON_PROV FOREIGN KEY (PROVINCIAID) REFERENCES PROVINCIAS(PROVINCIAID)
);

CREATE SEQUENCE SEQ_CANTON START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_CANTON_BI
BEFORE INSERT ON CANTONES
FOR EACH ROW
BEGIN
  IF :NEW.CANTONID IS NULL THEN
    :NEW.CANTONID := SEQ_CANTON.NEXTVAL;
  END IF;
END;
/

CREATE TABLE PARROQUIAS (
  PARROQUIAID NUMBER(10) PRIMARY KEY,
  CANTONID NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(200) NOT NULL,
  CONSTRAINT FK_PARROQUIA_CANTON FOREIGN KEY (CANTONID) REFERENCES CANTONES(CANTONID)
);

CREATE SEQUENCE SEQ_PARROQUIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_PARROQUIA_BI
BEFORE INSERT ON PARROQUIAS
FOR EACH ROW
BEGIN
  IF :NEW.PARROQUIAID IS NULL THEN
    :NEW.PARROQUIAID := SEQ_PARROQUIA.NEXTVAL;
  END IF;
END;
/
-- Sugerencia de carga: usa los archivos CSV del repo https://github.com/vfabianfarias/Datos-Geograficos-Ecuador
-- Puedes descargar los ficheros RAW y generar INSERTs o usar SQL*Loader / external table para cargarlos.
