-- Crea las tablas transaccionales base si no existen para que el plan pueda ejecutarse desde cero.
-- Cada bloque sólo ejecuta el DDL cuando la tabla correspondiente está ausente.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'CLIENTES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
CREATE TABLE CLIENTES (
    CLIENTEID NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    EMAIL VARCHAR2(150),
    TELEFONO VARCHAR2(30)
)
]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'PRODUCTOS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
CREATE TABLE PRODUCTOS (
    PRODUCTOID NUMBER(10) PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    PRECIOUNIT NUMBER(10,2),
    CATEGORIA VARCHAR2(100)
)
]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'ORDENES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
CREATE TABLE ORDENES (
    ORDENID NUMBER(10) PRIMARY KEY,
    CLIENTEID NUMBER(10) NOT NULL,
    EMPLEADOID NUMBER(10),
    FECHAORDEN DATE,
    DESCUENTO NUMBER(5,2) DEFAULT 0,
    CONSTRAINT FK_ORDENES_CLIENTES FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES(CLIENTEID)
)
]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'DETALLE_ORDENES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
CREATE TABLE DETALLE_ORDENES (
    DETALLEID NUMBER(10) PRIMARY KEY,
    ORDENID NUMBER(10) NOT NULL,
    PRODUCTOID NUMBER(10) NOT NULL,
    CANTIDAD NUMBER(10),
    PRECIOUNIT NUMBER(10,2),
    CONSTRAINT FK_DETALLE_ORDENES_ORDENES FOREIGN KEY (ORDENID) REFERENCES ORDENES(ORDENID),
    CONSTRAINT FK_DETALLE_ORDENES_PRODUCTOS FOREIGN KEY (PRODUCTOID) REFERENCES PRODUCTOS(PRODUCTOID)
)
]';
    END IF;
END;
/
