-- 02_add_ciudad_to_clientes.sql
-- Agrega columna CIUDADID a CLIENTES y la FK hacia CIUDAD

ALTER TABLE CLIENTES ADD (CIUDADID NUMBER(10));

ALTER TABLE CLIENTES ADD (
  CONSTRAINT FK_CLIENTES_CIUDAD FOREIGN KEY (CIUDADID) REFERENCES CIUDAD(CIUDADID)
);

COMMIT;
