-- Esquema geografico de Ecuador basado en el listado del censo 2016.
-- Crea PROVINCIAS, CANTONES y PARROQUIAS con claves surrogate y llaves foraneas.
-- Se separa codigo/nombre para facilitar futuras cargas via CSV/SQL*Loader.

CREATE TABLE PROVINCIAS (
    PROVINCIAID NUMBER(10)    PRIMARY KEY,
    CODIGO      VARCHAR2(10),
    NOMBRE      VARCHAR2(150) NOT NULL,
    CONSTRAINT UK_PROVINCIAS_CODIGO UNIQUE (CODIGO)
);

CREATE TABLE CANTONES (
    CANTONID    NUMBER(10)    PRIMARY KEY,
    PROVINCIAID NUMBER(10)    NOT NULL,
    CODIGO      VARCHAR2(10),
    NOMBRE      VARCHAR2(150) NOT NULL,
    CONSTRAINT FK_CANTON_PROVINCIA FOREIGN KEY (PROVINCIAID) REFERENCES PROVINCIAS(PROVINCIAID),
    CONSTRAINT UK_CANTONES_CODIGO UNIQUE (CODIGO)
);

CREATE TABLE PARROQUIAS (
    PARROQUIAID NUMBER(10)    PRIMARY KEY,
    CANTONID    NUMBER(10)    NOT NULL,
    CODIGO      VARCHAR2(15),
    NOMBRE      VARCHAR2(150) NOT NULL,
    TIPO        VARCHAR2(20),
    CONSTRAINT FK_PARROQUIA_CANTON FOREIGN KEY (CANTONID) REFERENCES CANTONES(CANTONID),
    CONSTRAINT UK_PARROQUIAS_CODIGO UNIQUE (CODIGO)
);

CREATE SEQUENCE SEQ_PROVINCIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CANTON    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PARROQUIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_PROVINCIA_BI
BEFORE INSERT ON PROVINCIAS
FOR EACH ROW
BEGIN
    IF :NEW.PROVINCIAID IS NULL THEN
        :NEW.PROVINCIAID := SEQ_PROVINCIA.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CANTON_BI
BEFORE INSERT ON CANTONES
FOR EACH ROW
BEGIN
    IF :NEW.CANTONID IS NULL THEN
        :NEW.CANTONID := SEQ_CANTON.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PARROQUIA_BI
BEFORE INSERT ON PARROQUIAS
FOR EACH ROW
BEGIN
    IF :NEW.PARROQUIAID IS NULL THEN
        :NEW.PARROQUIAID := SEQ_PARROQUIA.NEXTVAL;
    END IF;
END;
/
