-- 02_alter_clientes_add_ciudad.sql
-- Agrega columna CIUDADID a CLIENTES y la FK hacia CIUDAD

ALTER TABLE CLIENTES ADD (CIUDADID NUMBER(10));

ALTER TABLE CLIENTES ADD (
  CONSTRAINT FK_CLIENTES_CIUDAD FOREIGN KEY (CIUDADID) REFERENCES CIUDAD(CIUDADID)
);

COMMIT;
